{% set name = "datamatrix" %}
{% set pypiname = "python-" + name %}
{% set version = "0.14.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ pypiname[0] }}/{{ pypiname }}/{{ pypiname }}-{{ version }}.tar.gz
  sha256: c950603797695d07de1c1f27077c9773748839902a427c09cf2c8e006afa4e47

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - openpyxl
    - fastnumbers
    - prettytable

test:
  imports:
    - datamatrix
    - datamatrix._datamatrix
    - datamatrix.io
    - datamatrix.convert
    - datamatrix.operations
    - datamatrix.series
    - datamatrix.functional
  requires:
    - numpy
    - scipy

about:
  home: https://github.com/smathot/python-datamatrix
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: An intuitive, Pythonic way to work with tabular data
  doc_url: https://datamatrix.cogsci.nl
  dev_url: https://github.com/smathot/python-datamatrix

extra:
  recipe-maintainers:
    - dschreij
    - smathot
